// LOCALHOST
### Get all contacts
GET http://localhost:8080/
### Get contact by id
GET http://localhost:8080/67956a3a38bf56be9946930e
### Get contact by id
GET http://localhost:8080/67956a5238bf56be99469310
### Get contact by id
GET http://localhost:8080/67956a6538bf56be99469312
### Add new contact 
POST http://localhost:8080/ 
Content-Type: application/json

{
    "firstName": "Lola",
    "lastName": "Greebley",
    "email": "lgreeb@yahoo.com",
    "favoriteColor": "brown",
    "birthday": "1975-02-20"
}

### Update contact by id
PUT http://localhost:8080/67956a3a38bf56be9946930e
Content-Type: application/json

{
    "id": "67956a3a38bf56be9946930e",
    "firstName": "Craig",
    "lastName": "Curtland",
    "email": "ccland@tidyinc.com",
    "favoriteColor": "perriwinkle",
    "birthday": "1999-04-09"
}

### Delete contact by id
DELETE http://localhost:8080/67985fed642ac6bb8b50a7d3

// PRODUCTION Deploy
### Get contact by id
GET https://httprequests.onrender.com/67956a3a38bf56be9946930e
### Get contact by id
GET https://httprequests.onrender.com/67956a5238bf56be99469310
### Get contact by id
GET https://httprequests.onrender.com/67956a6538bf56be99469312
### Get all contacts
GET https://httprequests.onrender.com/
### Add new contact
POST https://httprequests.onrender.com/ 
Content-Type: application/json

{
    "firstName": "Lola",
    "lastName": "Greebley",
    "email": "lgreeb@yahoo.com",
    "favoriteColor": "brown",
    "birthday": "1975-02-20"
}

### Update contact by id
PUT https://httprequests.onrender.com/67956a3a38bf56be9946930e
Content-Type: application/json

{
    "id": "67956a3a38bf56be9946930e",
    "firstName": "Craig",
    "lastName": "Curtland",
    "email": "ccland@tidyinc.com",
    "favoriteColor": "perriwinkle",
    "birthday": "1999-04-09"
}

### Delete contact by id
DELETE https://httprequests.onrender.com/679906331fbf95f3e6ffaeac